= 1. tutorial
:toc:

The goals of the first tutorial are: general info, the basics of the compilation and representations of numbers.

== Getting to know the laboratory computers
The following steps will introduce you a Linux Operating System. In case of troubles, do not hesitate to
contact the teaching assistants.

1. Turn on the computer and choose an OS Linux.
2. Log-in to the system with your username and password (the same as in KOS).
3. Start an available web browser.
4. Visit the course page: https://courses.fit.cvut.cz/BIE-PA1/tutorials/01.html, log-in and search for the instructions.
5. Start Terminal (command line) and create the directory `PA1` in your home directory. Then create the directory `tut01` in `PA1`.
6. Switch to the newly created directory `~/PA1/tut01`.

[TIP]
====
You can use an available file explorer to create the folders, however it is recommended to try the command line tool.
You might find useful these commands when using the command line: `ls`, `cd`, `mkdir` and help `man`.
====

=== The solution for creating the directories

[source,bash]
----
username@pc101:~ $ mkdir PA1
username@pc101:~ $ cd PA1
username@pc101:~/PA1 $ mkdir tut01
username@pc101:~/PA1 $ cd tut01
username@pc101:~/PA1/tut01 $
----

You can use an option `-p` to create a full structure of directories

[source,bash]
----
username@pc101:~ $ mkdir -p PA1/tut01
username@pc101:~ $ cd PA1/tut01
username@pc101:~/PA1/tut01 $
----

== Compilation
Try to compile the source code below using the following steps.

1. Run a simple text editor (eg. `nano`, `vi`, `gedit`, `kate`, `Atom`,
   `VS Code`, ...)
2. Copy the source code below into the directory `~/PA1/tut01` with the name `hello_world.c`.
3. Compile the source code using the following command: `g++ -Wall -pedantic hello_world.c -o
   hello_world`.

[TIP]
====
You can use `TAB` key when typing a file name in the command line for automatic completion of the name.
====

[start=4]
. Compilation is successful if the `g++` command does not print anything. Check the existence of an
  executable file `hello_world` with the command `ls`.
. Execute the program by `./hello_world`. You should see the text `Hello World!`.
. If you decide to rewrite the program manually, double-check the typos. In the worst case,
  the program might not be compilable. It is easier to copy-an-paste (CTRL+C, CTRL+V) the whole text.
  In case of problems, you can download the source code from here: link:hello_world.c[hello_world.c].

[source,c]
----
#include <stdio.h>

int main ( void ) {
    printf( "Hello World!\n" );
    return 0;
}
----

=== Hints

1. Editors can be opened from a standard menu (similar to the Start menu in OS Windows), additionally
   they can be started from the running command line. In the latter case, it is beneficial to start
   an editor in the `background` mode using the character `&`, eg. `kate &`.
2. The character `~` means a home directory. Typically this is equal to `/home/<username>`, where
   `<username>` is a username of a currently logged user.

3. The command `g++` compiles the source code in {cpp} mode. It is possible to compile in C mode
   by using the compiler `gcc` or `clang`. The `g{plus}{plus}` tool is used by link:https://progtest.fit.cvut.cz[Progtest]
   which will be used for an automatic evaluation of your Homeworks and thus it is safer for you
   to use the same compilation tool. The options `-Wall -pedantic` (the cases are important) turn on
   almost all warnings during the compilations. These warning do not let the compilation fail, but
   they usually signal unusual behavior of a program. The warnings should be typically fixed.
   The option `-o <filename>` sets the name of an executable file (it could look like `-o hello_world.exe`
   on Windows).

4. Some programs can not be executed, especially when copied or downloaded from the Internet. In
   such cases it is necessary to first enable those for execution. You can do it by a command
   `chmod +x <filename>`.


== Numeral systems

1.  Convert these decimal numbers to binary: 1, 45, 265.
2.  Convert these binary numbers to decimal: `101101`, `1010011101`, `1010101101`, `1010`.
3.  Convert these decimal numbers to hexadecimal: `5`, `12`, `26526`.
4.  Convert these hexadecimal numbers to decimal: `0xABBA`, `0xBABA`, `0x1234567890ABCDEF`.
5.  Convert these binary numbers to hexadecimal and octal: `101101`, `1010011101`, `1010101101`, `1010`.
6.  Convert these decimal numbers to octal: `45`, `8`.
7.  Convert these octal numbers to hexadecimal and decimal: `075`, `045`.
8.  What is the decimal value of the octal number `078`?
9.  Assume that signed numbers are stored using `8` bits. Represent decimal numbers `-50`, `-1`, `0`, `50` and `200` using sign-and-magnitude representation. Then convert these numbers back to decimal. Discuss the representation of decimal values `20`, `200` and `2000`.
10. Will the results from the previous exercise change if we use `16` bits?
11. Assume that signed numbers are stored using `8` bits. Using sign-and-magnitude representation compute `20 + 12` and `-66 + -96`. Convert the results back to decimal.
12. Will the results from the previous exercise change if we use `16` bits?
13. Assume that signed numbers are stored using `8` bits. Represent decimal numbers `-50`, `-1`, `0`, `50` and `200` using two's complement code. Then convert these numbers back to decimal. Discuss the representation of decimal values `20`, `200` and `2000`.
14. Will the results from the previous exercise change if we use `16` bits?
15. Assume that signed numbers are stored using `8` bits. Using two's complement representation compute `20 + 12` and `-66 + -96`. Convert the results back to decimal.
16. Will the results from the previous exercise change if we use `16` bits?

== Exam exercise

Write a program that reads a number `n1`, a base `b1` in which the number `n1` is represented and
a base `b2` to which the number `n1` will be converted. The bases must be within `2 \<= b \<= 36`
and the number `n1` must be within `0 \<= n < 2^32^` in the decimal system.
